# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://sslee05.github.io 
baseurl: #https://sslee05.github.io 
title: SSLEE 일지
description: "software developer 로서 느낀점을 일지로 남긴것들"
keywords: 'jekyll,theme,gem-based,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/sslee05
    - name: instagram
      url:
    - name: linkedin
      url: https://www.linkedin.com/in/%EC%83%81%EC%84%9D-%EC%9D%B4-6b9ab0134/
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>SSLEE blog</h1>
  section2: <h2>SSLEE 일지</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/sslee05" title="View on GitHub"></a></div>
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: software developer 로서 느낀점을 일지로 남긴것들

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
